site_name: World History - Modern
site_description: An interactive intelligent textbook for World History - Modern from 1200CD to the present.
site_author: Dan McCreary
docs_dir: docs
theme:
  name: material

nav:
  - Home: index.md
  - World History Notes: world-history-notes.md
  - Course Description: course-description.md
  - Learning Graph:
      - Course Description Assessment: learning-graph/course-description-assessment.md
